name: Run domain checks
on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Run code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          ACTION: check
          PR_NUMBER: ${{ github.event.number }}
        with:
          command: run
