name: Rust - Check a Pull Request

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  ACTION: check
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    name: Analyzing changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - uses: Swatinem/rust-cache@v2
      with:
        env-vars: "CARGO CC CFLAGS CXX CMAKE RUST ACTION TOKEN"
        cache-all-crates: "true"
        save-if: "true"
    - uses: actions-rs/cargo@v1
      env:
        TOKEN: ${{ github.token }}
      with:
          command: run
